version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2117:2117"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "2115:2115"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: